services:
  meilisearch:
    # TODO Upgrade to v1.10
    image: getmeili/meilisearch:v1.8.0
    env_file:
      - ./.env
    ports:
      - "7700:7700"
    volumes:
      - "meilisearch:/meili_data:rw"

  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.2
    ports:
      - "6379:6379"
    volumes:
      - "keydb:/data:rw"

  aws:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: 'server /data --console-address ":9090"'
    volumes:
      - "aws:/data:rw"
    ports:
      - "9000:9000"
      - "9090:9090"

  twitter_scrapper:
    build:
      context: twitter-scrapper
    volumes:
      - "./twitter-scrapper/accounts.db:/srv/accounts.db:rw"
      - "./twitter-scrapper/accounts.db:/srv/accounts.txt:rw"
    ports:
      - "8080:8000"

volumes:
  aws:
  keydb:
  meilisearch:
  s3:
