when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            traces_sample_rate: 1.0
            profiles_sample_rate: 1.0
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'
        register_error_listener: false
        register_error_handler: false

    monolog:
       handlers:
           sentry:
               type: sentry
               level: !php/const Monolog\Logger::ERROR
               hub_id: Sentry\State\HubInterface

    services:
        Monolog\Processor\PsrLogMessageProcessor:
            tags: { name: monolog.processor, handler: sentry }
